name: Deploy Laravel Project to cPanel

on:
  push:
    branches:
      - main   # main ব্রাঞ্চে push করলে ট্রিগার হবে

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, intl, mysql, gd, xml, ctype, json, curl, tokenizer

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Upload files to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21
        local-dir: ./
        server-dir: /home/edunika1/cicd.edunika.com/
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          **/tests/**
          **/storage/logs/**
          **/.env

    - name: Run Artisan Commands on Server (via SSH)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home/edunika1/cicd.edunika.com
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
